In [1]:
import numpy as np

1. Create an appropriate array for each of the following.

In [2]:
# (1) Generate a 2 dimensional array with shape (2, 5) by randomly extracting 10 integers between 10 and 30 inclusive.
print(np.random.randint(10,30,(2,5)))

[[11 19 17 20 28]
 [15 22 12 18 15]]


In [3]:
# (2) Extract 9 random numbers from the standard normal distribution
#   and use them to create an array with shape (3, 3, 1).
print(np.random.randn(9).reshape((3,3,1)))

[[[-1.25076185]
  [ 1.3624365 ]
  [ 0.64340201]]

 [[ 1.44109448]
  [-0.19298739]
  [-0.23554747]]

 [[ 1.05341838]
  [-0.52998496]
  [ 1.18869849]]]


In [4]:
# (3) Randomly extract 6 real numbers between 0 and 1 and use them to create a one-dimensional array.
print(np.random.random(6))

[0.00818886 0.58130329 0.82458981 0.25284598 0.26638558 0.54915694]


In [5]:
# (4) Create a two-dimensional diagonal matrix with the diagonal elements 1, 1.5, 2, 2.5, ... , 4.
temp = np.linspace(1,4,7)
temp_eye = np.eye(len(temp))
for i,j in enumerate(temp):
    temp_eye[i,i] = j
print(temp_eye)

[[1.  0.  0.  0.  0.  0.  0. ]
 [0.  1.5 0.  0.  0.  0.  0. ]
 [0.  0.  2.  0.  0.  0.  0. ]
 [0.  0.  0.  2.5 0.  0.  0. ]
 [0.  0.  0.  0.  3.  0.  0. ]
 [0.  0.  0.  0.  0.  3.5 0. ]
 [0.  0.  0.  0.  0.  0.  4. ]]


2. Create Z, the 8×8 array filled with zeros by the code below and answer the following.  
Z = np.zeros((8,8), dtype=np.int64)

In [6]:
Z = np.zeros((8,8), dtype=np.int64)
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [7]:
# array([[0, 0, 0, 0, 0, 0, 0, 0],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 0, 0, 0, 0, 0, 0, 0],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 0, 0, 0, 0, 0, 0, 0],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 0, 0, 0, 0, 0, 0, 0],
#        [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int64)
for i in range(1,8,2):
    for j in range(0,8,2):
        Z[i,j]=1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [8]:
# (2) Write a code to modify Z as below.
# array([[0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0],
#        [0, 1, 0, 1, 0, 1, 0, 1],
#        [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int64)
Z = np.zeros((8,8), dtype=np.int64)
for i in range(8):
    temp = i%2
    for j in range((temp+1)%2,8,2):
        Z[i,j]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Create the 2-dimensional 6×5 ndarray as the picture below.  
<img src="5_3.png">

In [9]:
row = np.arange(0,60,10).reshape([-1,1])
col = np.arange(6)
temp = row+col
print(temp)

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [10]:
# (1) Write the code to select the values in orange box as a one-dimensional ndarray.
print(temp[0,[3,4]])

[3 4]


In [11]:
# (2) Write the code to select the values in cyan box as a two-dimensional ndarray with shape (2,2).
idx_row = []
idx_col = []
temp_row = [4,5]
temp_col = [4,5]
for i in temp_row:
    for j in temp_col:
        idx_row.append(i)
        idx_col.append(j)
print(temp[idx_row, idx_col].reshape(len(temp_row),len(temp_col)))

[[44 45]
 [54 55]]


In [12]:
# (3) Write the code to select the values in red box as a one-dimensional ndarray.
print(temp[:,2])

[ 2 12 22 32 42 52]


In [13]:
# (4) Write the code to select the values in red box as a two-dimensional ndarray with shape (6,1).
print(temp[:,2].reshape(6,1))

[[ 2]
 [12]
 [22]
 [32]
 [42]
 [52]]


In [14]:
# (5) Replace the values in red box with 0, 1, 2, 3, 4, 5 in order from the top.
temp[:,2] = np.arange(6)
print(temp)

[[ 0  1  0  3  4  5]
 [10 11  1 13 14 15]
 [20 21  2 23 24 25]
 [30 31  3 33 34 35]
 [40 41  4 43 44 45]
 [50 51  5 53 54 55]]


In [15]:
# (6) Write the code to select the values in light green part as a two-dimensional ndarray with shape (2, 3).
idx_row = []
idx_col = []
temp_row = [2,4]
temp_col = np.arange(0,5,2)
for i in temp_row:
    for j in temp_col:
        idx_row.append(i)
        idx_col.append(j)
print(temp[idx_row, idx_col].reshape(len(temp_row),len(temp_col)))

[[20  2 24]
 [40  4 44]]


In [16]:
# (7) Replace the values 20, 22(updated to 2 in (5)), 24, 40, 42(updated to 4 in (5)), 44 in light green box
#   with 1, 2, 3, 4, 5, 6, respectively.
temp[idx_row,idx_col] = np.arange(1,7)
print(temp)

[[ 0  1  0  3  4  5]
 [10 11  1 13 14 15]
 [ 1 21  2 23  3 25]
 [30 31  3 33 34 35]
 [ 4 41  5 43  6 45]
 [50 51  5 53 54 55]]


In [17]:
# 4. Modify the element z of the 1 dimensional array Z so that it is a scaled value
#   in the manner of (z-m) / (M-m), where m is the minimum value and M is the maximum value of Z.
# Z = np.random.rand(5)
Z = np.random.rand(5)
m = min(Z)
M = max(Z)
print(Z)
for i,z in enumerate(Z):
    Z[i] = (z-m) / (M-m)
print(Z)

[0.49236724 0.83075722 0.5859036  0.03865782 0.28005852]
[0.57279354 1.         0.69088019 0.         0.30476062]


In [18]:
# 5. Extract the integer part of the random array Z.
# Z = np.random.uniform(0,10,10)
Z = np.random.uniform(0,10,10)
print(Z)
print(np.floor(Z))

[6.7779851  1.4618845  4.92799722 0.19802264 9.3314448  0.07623936
 6.70510533 9.08496891 1.63688605 2.68776672]
[6. 1. 4. 0. 9. 0. 6. 9. 1. 2.]


In [19]:
# 6. Create a numpy array NP consisting of integers 1, 2, …, 100.
# Modify all the even numbers of NPs to be negative by multiplying their values by -1.
NP = np.arange(1,101)
print(NP)
for i,j in enumerate(NP):
    if j%2==0:
        NP[i] *= -1
print(NP)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[   1   -2    3   -4    5   -6    7   -8    9  -10   11  -12   13  -14
   15  -16   17  -18   19  -20   21  -22   23  -24   25  -26   27  -28
   29  -30   31  -32   33  -34   35  -36   37  -38   39  -40   41  -42
   43  -44   45  -46   47  -48   49  -50   51  -52   53  -54   55  -56
   57  -58   59  -60   61  -62   63  -64   65  -66   67  -68   69  -70
   71  -72   73  -74   75  -76   77  -78   79  -80   81  -82   83  -84
   85  -86   87  -88   89  -90   91  -92   93  -94   95  -96   97  -98
   99 -100]


In [20]:
# 7. Convert 20, 21, 22, ..., 30 degrees Celsius to Fahrenheit using the formula below. 
# F=9/5×C+32
print(9/5*np.arange(20,31)+32)

[68.  69.8 71.6 73.4 75.2 77.  78.8 80.6 82.4 84.2 86. ]


In [21]:
# Create a 6×4 ndarray 'mat' by the following code.
# >>> np.random.seed(123)
# >>> mat = np.random.randn(6, 4); mat
# array([[ -1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
#        [-0.57860025,  1.65143654, -2.42667924, -0.42891263],
#        [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
#        [ 1.49138963, -0.638902  , -0.44398196, -0.43435128],
#        [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ],
#        [ 0.73736858,  1.49073203, -0.93583387,  1.17582904]])
np.random.seed(123)
mat = np.random.randn(6, 4)
print(mat)

[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]
 [ 2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904]]


In [22]:
# 8. Calculate the exponentials of the values in the first column of mat
#   and add them to the last column (5th column) of the mat. The mat will be updated as below.
# array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471,  0.33768877],
#         …
#        [ 0.73736858,  1.49073203, -0.93583387,  1.17582904,  2.09042747]])
mat = np.hstack([mat,np.exp(mat[:,0]).reshape(-1,1)])
print(mat)

[[-1.0856306   0.99734545  0.2829785  -1.50629471  0.33768877]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263  0.56068263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897  3.54641154]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128  4.44326571]
 [ 2.20593008  2.18678609  1.0040539   0.3861864   9.07869158]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904  2.09042747]]


In [23]:
# 9. Modify the mat so that 1 is added to all elements in columns 1, 3, and 5,
# and -1 is added to all elements in columns 2 and 4. Use broadcasting rule.
temp = np.array([1,-1,1,-1,1])
mat += temp
print(mat)

[[-8.56306033e-02 -2.65455342e-03  1.28297850e+00 -2.50629471e+00
   1.33768877e+00]
 [ 4.21399748e-01  6.51436537e-01 -1.42667924e+00 -1.42891263e+00
   1.56068263e+00]
 [ 2.26593626e+00 -1.86674040e+00  3.21113848e-01 -1.09470897e+00
   4.54641154e+00]
 [ 2.49138963e+00 -1.63890200e+00  5.56018040e-01 -1.43435128e+00
   5.44326571e+00]
 [ 3.20593008e+00  1.18678609e+00  2.00405390e+00 -6.13813601e-01
   1.00786916e+01]
 [ 1.73736858e+00  4.90732028e-01  6.41661316e-02  1.75829045e-01
   3.09042747e+00]]


In [24]:
# 10. Modify mat so that all elements in rows 1, 2, and 3 are multiplied by 1/10,
# and all elements in rows 4, 5, and 6 are multiplied by 10. Use Broadcasting.
temp = np.array([1/10,1/10,1/10,10,10,10]).reshape(-1,1)
mat *= temp
print(mat)

[[-8.56306033e-03 -2.65455342e-04  1.28297850e-01 -2.50629471e-01
   1.33768877e-01]
 [ 4.21399748e-02  6.51436537e-02 -1.42667924e-01 -1.42891263e-01
   1.56068263e-01]
 [ 2.26593626e-01 -1.86674040e-01  3.21113848e-02 -1.09470897e-01
   4.54641154e-01]
 [ 2.49138963e+01 -1.63890200e+01  5.56018040e+00 -1.43435128e+01
   5.44326571e+01]
 [ 3.20593008e+01  1.18678609e+01  2.00405390e+01 -6.13813601e+00
   1.00786916e+02]
 [ 1.73736858e+01  4.90732028e+00  6.41661316e-01  1.75829045e+00
   3.09042747e+01]]


In [25]:
# 11. Calculate the median and 70-percentile for each column in mat. 
# print(np.sort(mat,axis=0))
# print((np.sort(mat,axis=0)[2]+np.sort(mat,axis=0)[3])/2)
print(np.median(mat,axis=0))
print(np.percentile(mat,axis=0,q=[70]))

[ 8.80013969  0.0324391   0.38497958 -0.19676037 15.67945792]
[[21.14379101  2.48623197  3.10092086 -0.12618108 42.66846589]]


In [26]:
# 12. Print the element in the third row of mat in descending order.
print(np.sort(mat[2])[::-1])
print(mat[2][np.argsort(-mat[2])])

[ 0.45464115  0.22659363  0.03211138 -0.1094709  -0.18667404]
[ 0.45464115  0.22659363  0.03211138 -0.1094709  -0.18667404]


In [27]:
# 13. Print out how many exponential values of elements in mat is greater than 3, for each row. 7
np.sum(np.exp(mat)>3,axis=1)

array([0, 0, 0, 3, 4, 4])

In [28]:
# 14. Calculate the average of each column of mat and
# Find the positions (row & column index) where each element of mat is larger than its column average.
print(np.mean(mat,axis=0))
print(np.array(np.nonzero(mat>np.mean(mat,axis=0))))
mat[np.nonzero(mat>np.mean(mat,axis=0))]

[12.4345089   0.04406089  4.376687   -3.20439166 31.14472097]
[[0 1 1 2 3 3 3 4 4 4 4 5 5 5]
 [3 1 3 3 0 2 4 0 1 2 4 0 1 3]]


array([-2.50629471e-01,  6.51436537e-02, -1.42891263e-01, -1.09470897e-01,
        2.49138963e+01,  5.56018040e+00,  5.44326571e+01,  3.20593008e+01,
        1.18678609e+01,  2.00405390e+01,  1.00786916e+02,  1.73736858e+01,
        4.90732028e+00,  1.75829045e+00])

In [29]:
# Create a 3×3 ndarray 'M' by the following code.
# >>> np.random.seed(123)
# >>> M = np.random.randint(1, 50, size=(3,3))
# >>> M
# array([[46,  3, 29],
#        [35, 39, 18],
#        [20, 43, 23]])
np.random.seed(123)
M = np.random.randint(1, 50, size=(3,3))
print(M)

[[46  3 29]
 [35 39 18]
 [20 43 23]]


In [30]:
# 15. Calculate the matrix multiplication of M and M transpose.
print(M.dot(M.T))
print(M@M.T)

[[2966 2249 1716]
 [2249 3070 2791]
 [1716 2791 2778]]
[[2966 2249 1716]
 [2249 3070 2791]
 [1716 2791 2778]]


In [31]:
# 16. Calculate the determinant of M.
print(np.linalg.det(M))

25347.999999999975


In [32]:
# 17. Calculate the inverse matrix of M.
print(np.linalg.inv(M))

[[ 0.00485245  0.04647309 -0.04248856]
 [-0.01755563  0.0188575   0.00737731]
 [ 0.02860186 -0.07566672  0.06663248]]
