In [1]:
import numpy as np

# 1. Using the following code, create a ndarray named "aMat".
```
np.random.seed(123)
aMat = np.random.randint(0, 100, (6, 10))
```

In [2]:
np.random.seed(123)
aMat = np.random.randint(0, 100, (6, 10))
print(aMat)

[[66 92 98 17 83 57 86 97 96 47]
 [73 32 46 96 25 83 78 36 96 80]
 [68 49 55 67  2 84 39 66 84 47]
 [61 48  7 99 92 52 97 85 94 27]
 [34 97 76 40  3 69 64 75 34 58]
 [10 22 77 18 15 27 30 52 70 26]]


(1)	Create a 1-dimensional ndarray "aVec" of length 10, of which element has a value 1
if the average of the corresponding column in "aMat" is greater than 50 and a value 0
if the average is less than or equal to 50. 

In [3]:
aVec = aMat.copy()
aVec[:,np.mean(aMat, axis=0)>50] = 1
aVec[:,np.mean(aMat, axis=0)<=50] = 0
print(aVec)

[[1 1 1 1 0 1 1 1 1 0]
 [1 1 1 1 0 1 1 1 1 0]
 [1 1 1 1 0 1 1 1 1 0]
 [1 1 1 1 0 1 1 1 1 0]
 [1 1 1 1 0 1 1 1 1 0]
 [1 1 1 1 0 1 1 1 1 0]]


(2)	Create a subarray of "aMat" consisting only the cases where the value in the 5th column is greater than 50
or the value in the 7th column is less than 30. 

In [4]:
print(aMat)
print(aMat[:,4][aMat[:,4]>50])
print(aMat[:,6][aMat[:,6]<30])
sub_aMat = np.append(aMat[:,4][aMat[:,4]>50], aMat[:,6][aMat[:,6]<30])
print(sub_aMat)

[[66 92 98 17 83 57 86 97 96 47]
 [73 32 46 96 25 83 78 36 96 80]
 [68 49 55 67  2 84 39 66 84 47]
 [61 48  7 99 92 52 97 85 94 27]
 [34 97 76 40  3 69 64 75 34 58]
 [10 22 77 18 15 27 30 52 70 26]]
[83 92]
[]
[83 92]


(3)	Modify the two elements, one in the 4th row and the 2nd column and
the other in the 2nd row and the 7th column of "aMat", to 999.

In [5]:
aMat[[3,1],[1,6]] = 999
print(aMat)

[[ 66  92  98  17  83  57  86  97  96  47]
 [ 73  32  46  96  25  83 999  36  96  80]
 [ 68  49  55  67   2  84  39  66  84  47]
 [ 61 999   7  99  92  52  97  85  94  27]
 [ 34  97  76  40   3  69  64  75  34  58]
 [ 10  22  77  18  15  27  30  52  70  26]]


(4)	Find the mean and standard deviation for each column of "aMat"
with the rows that contain any 999 removed. 

In [6]:
sub_aMat = np.delete(aMat,np.where(aMat==999)[0],0)
print(sub_aMat)
print(sub_aMat.mean(axis=0))
print(sub_aMat.std(axis=0))

[[66 92 98 17 83 57 86 97 96 47]
 [68 49 55 67  2 84 39 66 84 47]
 [34 97 76 40  3 69 64 75 34 58]
 [10 22 77 18 15 27 30 52 70 26]]
[44.5  65.   76.5  35.5  25.75 59.25 54.75 72.5  71.   44.5 ]
[24.05722345 31.05640031 15.20690633 20.37768387 33.44678609 20.93292861
 21.92458666 16.34778272 23.2594067  11.58663023]


(5)	Replace each 999 of "aMat" with the mean of the elements in its column.

In [7]:
aMat[np.where(aMat==999)] = np.mean(aMat[:,np.where(aMat==999)[1]],axis=0)
print(aMat)

[[ 66  92  98  17  83  57  86  97  96  47]
 [ 73  32  46  96  25  83 219  36  96  80]
 [ 68  49  55  67   2  84  39  66  84  47]
 [ 61 215   7  99  92  52  97  85  94  27]
 [ 34  97  76  40   3  69  64  75  34  58]
 [ 10  22  77  18  15  27  30  52  70  26]]


(6)	Using the "aMat" modified as above, create an expanded matrix "aMat2" of size,
which includes row sums, column sums and total sum of "aMat" in the following format.

<table>
    <tr>
        <th>"aMat"</th>
        <th>Row sums of "aMat"</th>
    </tr>
    <tr>
        <th>Column sums of "aMat"</th>
        <th>Total sum</th>
    </tr>
</table>


In [8]:
row_sums = np.sum(aMat, axis=1, keepdims=True)
column_sums = np.sum(aMat, axis=0, keepdims=True)
total_sum = np.sum(aMat)
column = np.append(column_sums,total_sum)
aMat2 = np.hstack([aMat,row_sums])
aMat2 = np.vstack([aMat2, column])
print(aMat2)

[[  66   92   98   17   83   57   86   97   96   47  739]
 [  73   32   46   96   25   83  219   36   96   80  786]
 [  68   49   55   67    2   84   39   66   84   47  561]
 [  61  215    7   99   92   52   97   85   94   27  829]
 [  34   97   76   40    3   69   64   75   34   58  550]
 [  10   22   77   18   15   27   30   52   70   26  347]
 [ 312  507  359  337  220  372  535  411  474  285 3812]]


2. Using the following code, create a ndarray named "MAT".
```
np.random.seed(123)
MAT = np.random.exponential(scale=1/5, size=(10, 7))
MAT= np.around( MAT, decimals=3 )
```

In [9]:
np.random.seed(123)
MAT = np.random.exponential(scale=1/5, size=(10, 7))
MAT = np.around( MAT, decimals=3 )
print(MAT)

[[0.238 0.067 0.051 0.16  0.254 0.11  0.79 ]
 [0.231 0.131 0.1   0.084 0.261 0.115 0.012]
 [0.102 0.268 0.04  0.039 0.152 0.152 0.201]
 [0.379 0.258 0.189 0.256 0.078 0.09  0.052]
 [0.07  0.199 0.019 0.114 0.113 0.136 0.111]
 [0.075 0.111 0.448 0.577 0.139 0.196 0.025]
 [0.076 0.107 0.402 0.058 0.132 0.848 0.147]
 [0.19  0.026 0.35  0.185 0.158 0.084 0.073]
 [0.108 0.229 0.417 0.143 0.221 0.176 0.196]
 [0.225 0.369 0.017 0.289 0.056 0.043 0.17 ]]


Extract all the elements (outliers) that are smaller than Q1-1.5×(Q3-Q1) or larger than Q3 + 1.5× (Q3-Q1)
where Q1 and Q3 are the 25th and the 75th percentile of "MAT", respectively.

In [10]:
Q1, Q3 = np.percentile(MAT,[25,75])
out_small = Q1 - 1.5 * (Q3 - Q1)
out_large = Q3 + 1.5 * (Q3 - Q1)
print(out_small)
print(out_large)
print(MAT[(MAT<out_small)|(MAT>out_large)])

-0.14325000000000004
0.45075000000000004
[0.79  0.577 0.848]


(2)	Find the element closest to the median in “MAT”, and print the row and column index of that element. 

In [11]:
print(np.median(MAT))
temp_MAT = np.abs(MAT - np.median(MAT))
print(temp_MAT[temp_MAT==np.min(temp_MAT)])
row, col = np.where(temp_MAT==np.min(temp_MAT))
print(f"row index : {row},\tcol index : {col}")
print(MAT[row,col])

0.14100000000000001
[0.002]
row index : [8],	col index : [3]
[0.143]


(3)	Arrange the rows of “MAT” so that elements in the 2nd column of “MAT” are sorted in ascending order.
(use np.argsort)

In [12]:
print(MAT[np.argsort(MAT[:,1])])

[[0.19  0.026 0.35  0.185 0.158 0.084 0.073]
 [0.238 0.067 0.051 0.16  0.254 0.11  0.79 ]
 [0.076 0.107 0.402 0.058 0.132 0.848 0.147]
 [0.075 0.111 0.448 0.577 0.139 0.196 0.025]
 [0.231 0.131 0.1   0.084 0.261 0.115 0.012]
 [0.07  0.199 0.019 0.114 0.113 0.136 0.111]
 [0.108 0.229 0.417 0.143 0.221 0.176 0.196]
 [0.379 0.258 0.189 0.256 0.078 0.09  0.052]
 [0.102 0.268 0.04  0.039 0.152 0.152 0.201]
 [0.225 0.369 0.017 0.289 0.056 0.043 0.17 ]]


(4)	Arrange the columns of “MAT” so that the average of each column of MAT is in descending order.
(use np.argsort)

In [13]:
print(np.mean(MAT, axis=0))
print(np.mean(MAT,axis=0)[np.argsort(-np.mean(MAT, axis=0))])

[0.1694 0.1765 0.2033 0.1905 0.1564 0.195  0.1777]
[0.2033 0.195  0.1905 0.1777 0.1765 0.1694 0.1564]


(5)	Using numerical indexing, extract the shaded elements of “MAT” so that they look like the following :  
①
```
array([[0.067, 0.16 , 0.254],
       [0.268, 0.039, 0.152]])
```

In [14]:
print(np.where((MAT==0.067)|(MAT==0.16)|(MAT==0.254)|(MAT==0.268)|(MAT==0.039)|(MAT==0.152)))
print(MAT[[0, 0, 0, 2, 2, 2],[1, 3, 4, 1, 3, 4]].reshape(2,3))

(array([0, 0, 0, 2, 2, 2, 2], dtype=int64), array([1, 3, 4, 1, 3, 4, 5], dtype=int64))
[[0.067 0.16  0.254]
 [0.268 0.039 0.152]]


②
```
array([0.067, 0.16 , 0.254, 0.268, 0.039, 0.152])
```

In [15]:
print(MAT[[0, 0, 0, 2, 2, 2],[1, 3, 4, 1, 3, 4]])

[0.067 0.16  0.254 0.268 0.039 0.152]


(6)	Replace all the elements which are detected to be as outliers in 1 to NaN.

In [16]:
outliers = MAT[(MAT<out_small)|(MAT>out_large)]
print(outliers)
MAT[(MAT<out_small)|(MAT>out_large)] = np.nan
print(MAT)

[0.79  0.577 0.848]
[[0.238 0.067 0.051 0.16  0.254 0.11    nan]
 [0.231 0.131 0.1   0.084 0.261 0.115 0.012]
 [0.102 0.268 0.04  0.039 0.152 0.152 0.201]
 [0.379 0.258 0.189 0.256 0.078 0.09  0.052]
 [0.07  0.199 0.019 0.114 0.113 0.136 0.111]
 [0.075 0.111 0.448   nan 0.139 0.196 0.025]
 [0.076 0.107 0.402 0.058 0.132   nan 0.147]
 [0.19  0.026 0.35  0.185 0.158 0.084 0.073]
 [0.108 0.229 0.417 0.143 0.221 0.176 0.196]
 [0.225 0.369 0.017 0.289 0.056 0.043 0.17 ]]


(7)	In MAT, extract the rows that contain at least one NaN.

In [17]:
print(np.where(np.isnan(MAT))[0])

[0 5 6]
